version: "3.9"
services:
  sideburn-web:
    restart: always
    container_name: sideburn-web
    build: ./sideburn-web/
    ports:
      - "8585:80"
  sideburn-db:
    # image: couchdb
    build: ./sideburn-db/
    container_name: sideburn-db
    restart: always
    environment:
      - 'COUCHDB_USER=${COUCHDB_USER}'
      - 'COUCHDB_PASSWORD=${COUCHDB_PASSWORD}'
    volumes:
      - "./sideburn-db/couchdb/data:/opt/couchdb/data"
    ports:
      - "5984:5984"
  sideburn-api:
    restart: always
    container_name: sideburn-api
    build: ./sideburn-api/
    links: ['sideburn-db']
    environment:
      - 'COUCHDB_USER=${COUCHDB_USER}'
      - 'COUCHDB_PASSWORD=${COUCHDB_PASSWORD}'
    ports:
      - "8686:8080"
