version: "3.9"

services:
  web:
    image: bisand/sideburnwhisky-web
    restart: always
    ports:
      - "8585:80"
  db:
    image: bisand/sideburnwhisky-db
    restart: always
    environment:
      - 'COUCHDB_USER=${COUCHDB_USER}'
      - 'COUCHDB_PASSWORD=${COUCHDB_PASSWORD}'
    volumes:
      - "couchdb-data:/opt/couchdb/data"
    ports:
      - "${COUCHDB_PORT}:${COUCHDB_PORT}"
  api:
    image: bisand/sideburnwhisky-api
    restart: always
    links: ['db']
    environment:
      - 'COUCHDB_USER=${COUCHDB_USER}'
      - 'COUCHDB_PASSWORD=${COUCHDB_PASSWORD}'
      - 'COUCHDB_HOST=${COUCHDB_HOST}'
      - 'COUCHDB_PORT=${COUCHDB_PORT}'
      - 'COUCHDB_DATABASE=${COUCHDB_DATABASE}'
    ports:
      - "8686:8080"

volumes:
  couchdb-data:
