version: "3.9"

services:
  web:
    restart: always
    container_name: web
    build: ./web/
    ports:
      - "8585:80"
  db:
    build: ./db/
    container_name: db
    restart: always
    environment:
      - 'COUCHDB_USER=${COUCHDB_USER}'
      - 'COUCHDB_PASSWORD=${COUCHDB_PASSWORD}'
    volumes:
      - "./db/couchdb/data:/opt/couchdb/data"
    ports:
      - "${COUCHDB_PORT}:${COUCHDB_PORT}"
  api:
    restart: always
    container_name: api
    build: ./api/
    links: ['db']
    environment:
      - 'COUCHDB_USER=${COUCHDB_USER}'
      - 'COUCHDB_PASSWORD=${COUCHDB_PASSWORD}'
      - 'COUCHDB_HOST=${COUCHDB_HOST}'
      - 'COUCHDB_PORT=${COUCHDB_PORT}'
      - 'COUCHDB_DATABASE=${COUCHDB_DATABASE}'
    ports:
      - "8686:8080"
