version: "3.9"

services:
  web:
    restart: always
    container_name: web
    build: ./web/
    # volumes:
    #   - web_data:/usr/share/nginx/html:ro
    #   - nginx_config:/etc/nginx:ro
    ports:
      - "8585:80"
  db:
    # image: couchdb
    build: ./db/
    container_name: db
    restart: always
    environment:
      - 'COUCHDB_USER=${COUCHDB_USER}'
      - 'COUCHDB_PASSWORD=${COUCHDB_PASSWORD}'
    volumes:
      - "./db/couchdb/data:/opt/couchdb/data"
    ports:
      - "5984:5984"
  api:
    restart: always
    container_name: api
    build: ./api/
    links: ['db']
    environment:
      - 'COUCHDB_USER=${COUCHDB_USER}'
      - 'COUCHDB_PASSWORD=${COUCHDB_PASSWORD}'
      - 'COUCHDB_HOST=${COUCHDB_HOST}'
      - 'COUCHDB_PORT=${COUCHDB_PORT}'
      - 'COUCHDB_DATABASE=${COUCHDB_DATABASE}'
    ports:
      - "8686:8080"

# volumes:
#   nginx_config:
#   web_data:
    # driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: './.volumes/web/html'

