version: "3.9"
services:
  web:
    restart: always
    container_name: web
    build: ./sideburn-web/
    ports:
      - "8585:80"
  db:
    # image: couchdb
    build: ./sideburn-db/
    container_name: db
    restart: always
    environment:
      - 'COUCHDB_USER=${COUCHDB_USER}'
      - 'COUCHDB_PASSWORD=${COUCHDB_PASSWORD}'
    volumes:
      - "./sideburn-db/couchdb/data:/opt/couchdb/data"
    ports:
      - "5984:5984"
  api:
    restart: always
    container_name: api
    build: ./sideburn-api/
    links: ['db']
    environment:
      - 'COUCHDB_USER=${COUCHDB_USER}'
      - 'COUCHDB_PASSWORD=${COUCHDB_PASSWORD}'
    ports:
      - "8686:8080"
